// Contents of "acme-system.yang"
// example of YANG data modelling module

module acme-system{
    namespace "http://acme.example.com/system";
    prefix "acme";

    organization "ACME inc";
    descripton "The module for entities for implementing ACME system.";

    revision 2007-01-01{
        descripton "initial revision"
    }

    container system{
        leaf host-name{
            type string;
            descripton "hostname for this system";
        }

        leaf-list domain-search{
            type string;
            descripton "list of domain names to search";
        }
        container login{
            leaf message{
                type string;
                descripton
                "Message given at start of login session";
                "This is the yang login session"
            }

            list user{
                key "name";
                leaf name{
                    type string;
                }
                leaf full-name{
                    type string;

                }
                leaf class{
                    type string;
                }
            }
        }
    }
}